// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aszzfzlbdhvukkfciatx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzenpmemxiZGh2dWtrZmNpYXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDc5MzUsImV4cCI6MjA2NzU4MzkzNX0.eONQ225VeL4kFAGsP0OOeK2dLdffflnEDpOMpUUBmXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});